package com.vaibhav.covid19.ui.home;

import android.os.Bundle;

import androidx.fragment.app.Fragment;
import androidx.fragment.app.FragmentManager;
import androidx.fragment.app.FragmentTransaction;

import android.text.TextUtils;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.Toast;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.vaibhav.covid19.R;

import java.net.NetworkInterface;
import java.util.Collections;
import java.util.List;

public class FormFragment extends Fragment {

    private AutoCompleteTextView cityEditText, stateEditText, countryEditText;

    private EditText nameEditText, nameLastEditText, numberEditText,addressEditText;

    private String latitude, longitude;

    private Button submitButton;

    private DatabaseReference mFirebase;

    private Upload upload;



    private static final String[] NameCountry = new String[] {
            "Iran",
            "Spain",
            "Germany",
            "USA",
            "France",
            "South Korea",
            "Switzerland",
            "UK",
            "India",
            "Australia",
            "Israel",
            "Singapore",
            "China"
    };

    private static final String[] NameState = new String[]{"Andhra Pradesh",
            "Arunachal Pradesh",
            "Assam",
            "Bihar",
            "Chhattisgarh",
            "Goa",
            "Gujarat",
            "Haryana",
            "Himachal Pradesh",
            "Jammu and Kashmir",
            "Jharkhand",
            "Karnataka",
            "Kerala",
            "Madhya Pradesh",
            "Maharashtra",
            "Manipur",
            "Meghalaya",
            "Mizoram",
            "Nagaland",
            "Odisha",
            "Punjab",
            "Rajasthan",
            "Sikkim",
            "Tamil Nadu",
            "Telangana",
            "Tripura",
            "Uttarakhand",
            "Uttar Pradesh",
            "West Bengal",
            "Andaman and Nicobar Islands",
            "Chandigarh",
            "Dadra and Nagar Haveli",
            "Daman and Diu",
            "Delhi",
            "Lakshadweep",
            "Puducherry"
    };

    private static final String[] Namee = new String[]{"Adilabad","Agra",
            "Ahmedabad",
            "Ahmednagar",
            "Aizawl",
            "Ajitgarh",
            "Ajmer",
            "Akola",
            "Alappuzha",
            "Aligarh",
            "Alirajpur",
            "Allahabad",
            "Almora",
            "Alwar",
            "Ambala",
            "Ambedkar Nagar",
            "Amravati",
            "Amreli district",
            "Amritsar",
            "Anand",
            "Anantapur",
            "Anantnag",
            "Angul",
            "Anjaw",
            "Anuppur",
            "Araria",
            "Ariyalur",
            "Arwal",
            "Ashok Nagar",
            "Auraiya",
            "Aurangabad",
            "Aurangabad",
            "Azamgarh",
            "Badgam",
            "Bagalkot",
            "Bageshwar",
            "Bagpat",
            "Bahraich",
            "Baksa",
            "Balaghat",
            "Balangir",
            "Balasore",
            "Ballia",
            "Balrampur",
            "Banaskantha",
            "Banda",
            "Bandipora",
            "Bangalore Rural",
            "Bangalore Urban",
            "Banka",
            "Bankura",
            "Banswara",
            "Barabanki",
            "Baramulla",
            "Baran",
            "Bardhaman",
            "Bareilly",
            "Bargarh (Baragarh)",
            "Barmer",
            "Barnala",
            "Barpeta",
            "Barwani",
            "Bastar",
            "Basti",
            "Bathinda",
            "Beed",
            "Begusarai",
            "Belgaum",
            "Bellary",
            "Betul",
            "Bhadrak",
            "Bhagalpur",
            "Bhandara",
            "Bharatpur",
            "Bharuch",
            "Bhavnagar",
            "Bhilwara",
            "Bhind",
            "Bhiwani",
            "Bhojpur",
            "Bhopal",
            "Bidar",
            "Bijapur",
            "Bijapur",
            "Bijnor",
            "Bikaner",
            "Bilaspur",
            "Bilaspur",
            "Birbhum",
            "Bishnupur",
            "Bokaro",
            "Bongaigaon",
            "Boudh (Bauda)",
            "Budaun",
            "Bulandshahr",
            "Buldhana",
            "Bundi",
            "Burhanpur",
            "Buxar",
            "Cachar",
            "Central Delhi",
            "Chamarajnagar",
            "Chamba",
            "Chamoli",
            "Champawat",
            "Champhai",
            "Chandauli",
            "Chandel",
            "Chandigarh",
            "Chandrapur",
            "Changlang",
            "Chatra",
            "Chennai",
            "Chhatarpur",
            "Chhatrapati Shahuji Maharaj Nagar",
            "Chhindwara",
            "Chikkaballapur",
            "Chikkamagaluru",
            "Chirang",
            "Chitradurga",
            "Chitrakoot",
            "Chittoor",
            "Chittorgarh",
            "Churachandpur",
            "Churu",
            "Coimbatore",
            "Cooch Behar",
            "Cuddalore",
            "Cuttack",
            "Dadra and Nagar Haveli",
            "Dahod",
            "Dakshin Dinajpur",
            " Dakshina Kannada",
            "Daman",
            "Damoh",
            "Dantewada",
            "Darbhanga",
            "Darjeeling",
            "Darrang",
            "Datia",
            "Dausa",
            "Davanagere",
            "Debagarh (Deogarh)",
            "Dehradun",
            "Deoghar",
            "Deoria",
            "Dewas",
            "Dhalai",
            "Dhamtari",
            "Dhanbad",
            "Dhar",
            "Dharmapuri",
            "Dharwad",
            "Dhemaji",
            "Dhenkanal",
            "Dholpur",
            "Dhubri",
            "Dhule",
            "Dibang Valley",
            "Dibrugarh",
            "Dima Hasao",
            "Dimapur",
            "Dindigul",
            "Dindori",
            "Diu",
            "Doda",
            "Dumka",
            "Dungapur",
            "Durg",
            "East Champaran",
            "East Delhi",
            "East Garo Hills",
            "East Khasi Hills",
            "East Siang",
            "East Sikkim",
            "East Singhbhum",
            "Eluru",
            "Ernakulam",
            "Erode",
            "Etah",
            "Etawah",
            "Faizabad",
            "Faridabad",
            "Faridkot",
            "Farrukhabad",
            "Fatehabad",
            "Fatehgarh Sahib",
            "Fatehpur",
            "Fazilka",
            "Firozabad",
            "Firozpur",
            "Gadag",
            "Gadchiroli",
            "Gajapati",
            "Ganderbal",
            "Gandhinagar",
            "Ganganagar",
            "Ganjam",
            "Garhwa",
            "Gautam Buddh Nagar",
            "Gaya",
            "Ghaziabad",
            "Ghazipur",
            "Giridih",
            "Goalpara",
            "Godda",
            "Golaghat",
            "Gonda",
            "Gondia",
            "Gopalganj",
            "Gorakhpur",
            "Gulbarga",
            "Gumla",
            "Guna",
            "Guntur",
            "Gurdaspur",
            "Gurgaon",
            "Gwalior",
            "Hailakandi",
            "Hamirpur",
            "Hanumangarh",
            "Harda",
            "Hardoi",
            "Haridwar",
            "Hassan",
            "Haveri district",
            "Hazaribag",
            "Hingoli",
            "Hissar",
            "Hooghly",
            "Hoshangabad",
            "Hoshiarpur",
            "Howrah",
            "Hyderabad",
            "Idukki",
            "Imphal East",
            "Imphal West",
            "Indore",
            "Jabalpur",
            "Jagatsinghpur",
            "Jaintia Hills",
            "Jaipur",
            "Jaisalmer",
            "Jajpur",
            "Jalandhar",
            "Jalaun",
            "Jalgaon",
            "Jalna",
            "Jalore",
            "Jalpaiguri",
            "Jammu",
            "Jamnagar",
            "Jamtara",
            "Jamui",
            "Janjgir-Champa",
            "Jashpur",
            "Jaunpur district",
            "Jehanabad",
            "Jhabua",
            "Jhajjar",
            "Jhalawar",
            "Jhansi",
            "Jharsuguda",
            "Jhunjhunu",
            "Jind",
            "Jodhpur",
            "Jorhat",
            "Junagadh",
            "Jyotiba Phule Nagar",
            "Kabirdham (formerly Kawardha)",
            "Kadapa",
            "Kaimur",
            "Kaithal",
            "Kakinada",
            "Kalahandi",
            "Kamrup",
            "Kamrup Metropolitan",
            "Kanchipuram",
            "Kandhamal",
            "Kangra",
            "Kanker",
            "Kannauj",
            "Kannur",
            "Kanpur",
            "Kanshi Ram Nagar",
            "Kanyakumari",
            "Kapurthala",
            "Karaikal",
            "Karauli",
            "Karbi Anglong",
            "Kargil",
            "Karimganj",
            "Karimnagar",
            "Karnal",
            "Karur",
            "Kasaragod",
            "Kathua",
            "Katihar",
            "Katni",
            "Kaushambi",
            "Kendrapara",
            "Kendujhar (Keonjhar)",
            "Khagaria",
            "Khammam",
            "Khandwa (East Nimar)",
            "Khargone (West Nimar)",
            "Kheda",
            "Khordha",
            "Khowai",
            "Khunti",
            "Kinnaur",
            "Kishanganj",
            "Kishtwar",
            "Kodagu",
            "Koderma",
            "Kohima",
            "Kokrajhar",
            "Kolar",
            "Kolasib",
            "Kolhapur",
            "Kolkata",
            "Kollam",
            "Koppal",
            "Koraput",
            "Korba",
            "Koriya",
            "Kota",
            "Kottayam",
            "Kozhikode",
            "Krishna",
            "Kulgam",
            "Kullu",
            "Kupwara",
            "Kurnool",
            "Kurukshetra",
            "Kurung Kumey",
            "Kushinagar",
            "Kutch",
            "Lahaul and Spiti",
            "Lakhimpur",
            "Lakhimpur Kheri",
            "Lakhisarai",
            "Lalitpur",
            "Latehar",
            "Latur",
            "Lawngtlai",
            "Leh",
            "Lohardaga",
            "Lohit",
            "Lower Dibang Valley",
            "Lower Subansiri",
            "Lucknow",
            "Ludhiana",
            "Lunglei",
            "Madhepura",
            "Madhubani",
            "Madurai",
            "Mahamaya Nagar",
            "Maharajganj",
            "Mahasamund",
            "Mahbubnagar",
            "Mahe",
            "Mahendragarh",
            "Mahoba",
            "Mainpuri",
            "Malappuram",
            "Maldah",
            "Malkangiri",
            "Mamit",
            "Mandi",
            "Mandla",
            "Mandsaur",
            "Mandya",
            "Mansa",
            "Marigaon",
            "Mathura",
            "Mau",
            "Mayurbhanj",
            "Medak",
            "Meerut",
            "Mehsana",
            "Mewat",
            "Mirzapur",
            "Moga",
            "Mokokchung",
            "Mon",
            "Moradabad",
            "Morena",
            "Mumbai City",
            "Mumbai suburban",
            "Munger",
            "Murshidabad",
            "Muzaffarnagar",
            "Muzaffarpur",
            "Mysore",
            "Nabarangpur",
            "Nadia",
            "Nagaon",
            "Nagapattinam",
            "Nagpur",
            "Nainital",
            "Nalanda",
            "Nalbari",
            "Nalgonda",
            "Namakkal",
            "Nanded",
            "Nandurbar",
            "Narayanpur",
            "Narmada",
            "Narsinghpur",
            "Nashik",
            "Navsari",
            "Nawada",
            "Nawanshahr",
            "Nayagarh",
            "Neemuch",
            "Nellore",
            "New Delhi",
            "Nilgiris",
            "Nizamabad",
            "North 24 Parganas",
            "North Delhi",
            "North East Delhi",
            "North Goa",
            "North Sikkim",
            "North Tripura",
            "North West Delhi",
            "Nuapada",
            "Ongole",
            "Osmanabad",
            "Pakur",
            "Palakkad",
            "Palamu",
            "Pali",
            "Palwal",
            "Panchkula",
            "Panchmahal",
            " Panchsheel Nagar district (Hapur)",
            "Panipat",
            "Panna",
            "Papum Pare",
            "Parbhani",
            "Paschim Medinipur",
            "Patan",
            "Pathanamthitta",
            "Pathankot",
            "Patiala",
            "Patna",
            "Pauri Garhwal",
            "Perambalur",
            "Phek",
            "Pilibhit",
            "Pithoragarh",
            "Pondicherry",
            "Poonch",
            "Porbandar",
            "Pratapgarh",
            "Pratapgarh",
            "Pudukkottai",
            "Pulwama",
            "Pune",
            "Purba Medinipur",
            "Puri",
            "Purnia",
            "Purulia",
            "Raebareli",
            "Raichur",
            "Raigad",
            "Raigarh",
            "Raipur",
            "Raisen",
            "Rajauri",
            "Rajgarh",
            "Rajkot",
            "Rajnandgaon",
            "Rajsamand",
            "Ramabai Nagar (Kanpur Dehat)",
            "Ramanagara",
            "Ramanathapuram",
            "Ramban",
            "Ramgarh",
            "Rampur",
            "Ranchi",
            "Ratlam",
            "Ratnagiri",
            "Rayagada",
            "Reasi",
            "Rewa",
            "Rewari",
            "Ri Bhoi",
            "Rohtak",
            "Rohtas",
            "Rudraprayag",
            "Rupnagar",
            "Sabarkantha",
            "Sagar",
            "Saharanpur",
            "Saharsa",
            "Sahibganj",
            "Saiha",
            "Salem",
            "Samastipur",
            "Samba",
            "Sambalpur",
            "Sangli",
            "Sangrur",
            "Sant Kabir Nagar",
            "Sant Ravidas Nagar",
            "Saran",
            "Satara",
            "Satna",
            "Sawai Madhopur",
            "Sehore",
            "Senapati",
            "Seoni",
            "Seraikela Kharsawan",
            "Serchhip",
            "Shahdol",
            "Shahjahanpur",
            "Shajapur",
            "Shamli",
            "Sheikhpura",
            "Sheohar",
            "Sheopur",
            "Shimla",
            "Shimoga",
            "Shivpuri",
            "Shopian",
            "Shravasti",
            "Sibsagar",
            "Siddharthnagar",
            "Sidhi",
            "Sikar",
            "Simdega",
            "Sindhudurg",
            "Singrauli",
            "Sirmaur",
            "Sirohi",
            "Sirsa",
            "Sitamarhi",
            "Sitapur",
            "Sivaganga",
            "Siwan",
            "Solan",
            "Solapur",
            "Sonbhadra",
            "Sonipat",
            "Sonitpur",
            "South 24 Parganas",
            "South Delhi",
            "South Garo Hills",
            "South Goa",
            "South Sikkim",
            "South Tripura",
            "South West Delhi",
            "Sri Muktsar Sahib",
            "Srikakulam",
            "Srinagar",
            "Subarnapur (Sonepur)",
            "Sultanpur",
            "Sundergarh",
            "Supaul",
            "Surat",
            "Surendranagar",
            "Surguja",
            "Tamenglong",
            "Tarn Taran",
            "Tawang",
            "Tehri Garhwal",
            "Thane",
            "Thanjavur",
            "The Dangs",
            "Theni",
            "Thiruvananthapuram",
            "Thoothukudi",
            "Thoubal",
            "Thrissur",
            "Tikamgarh",
            "Tinsukia",
            "Tirap",
            "Tiruchirappalli",
            "Tirunelveli",
            "Tirupur",
            "Tiruvallur",
            "Tiruvannamalai",
            "Tiruvarur",
            "Tonk",
            "Tuensang",
            "Tumkur",
            "Udaipur",
            "Udalguri",
            "Udham Singh Nagar",
            "Udhampur",
            "Udupi",
            "Ujjain",
            "Ukhrul",
            "Umaria",
            "Una",
            "Unnao",
            "Upper Siang",
            "Upper Subansiri",
            "Uttar Dinajpur",
            "Uttara Kannada",
            "Uttarkashi",
            "Vadodara",
            "Vaishali",
            "Valsad",
            "Varanasi",
            "Vellore",
            "Vidisha",
            "Viluppuram",
            "Virudhunagar",
            "Visakhapatnam",
            "Vizianagaram",
            "Vyara",
            "Warangal",
            "Wardha",
            "Washim",
            "Wayanad",
            "West Champaran",
            "West Delhi",
            "West Garo Hills",
            "West Kameng",
            "West Khasi Hills",
            "West Siang",
            "West Sikkim",
            "West Singhbhum",
            "West Tripura",
            "Wokha",
            "Yadgir",
            "Yamuna Nagar",
            "Yanam",
            "Yavatmal",
            "Zunheboto"};

    private FrameLayout fl;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {

        View root = inflater.inflate(R.layout.fragment_form2, container, false);

        fl = (FrameLayout) root.findViewById(R.id.fragment_container);


        Bundle bundle = this.getArguments();
        latitude = bundle.getString("latitude");
        longitude = bundle.getString("longitude");
        //Toast.makeText(getActivity(), "new Latitude:" + latitude + ", Longitude:" + longitude, Toast.LENGTH_SHORT).show();

        nameEditText = (EditText) root.findViewById(R.id.nameEditText);
        nameLastEditText = (EditText) root.findViewById(R.id.nameLastEditText);
        cityEditText = root.findViewById(R.id.cityEditText);
        stateEditText = root.findViewById(R.id.stateEditText);
        countryEditText = root.findViewById(R.id.countryEditText);
        numberEditText = (EditText) root.findViewById(R.id.numberEditText);
        addressEditText = (EditText) root.findViewById(R.id.addressEditText);

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(getActivity(),android.R.layout.simple_list_item_1,Namee);
        cityEditText.setAdapter(adapter);

        ArrayAdapter<String> adapter1 = new ArrayAdapter<String>(getActivity(),android.R.layout.simple_list_item_1,NameState);
        stateEditText.setAdapter(adapter1);

        ArrayAdapter<String> adapter2 = new ArrayAdapter<String>(getActivity(),android.R.layout.simple_list_item_1,NameCountry);
        countryEditText.setAdapter(adapter2);

        submitButton = (Button) root.findViewById(R.id.submitButton);

        submitButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if(fieldEntry()) {
                    String mac = getMacAddr();
                    upload = new Upload(nameEditText.getText().toString().trim() + " " + nameLastEditText.getText().toString().trim(), addressEditText.getText().toString().trim() , cityEditText.getText().toString().trim(), stateEditText.getText().toString().trim(), countryEditText.getText().toString().trim() ,numberEditText.getText().toString().trim(), latitude, longitude,mac);
                    mFirebase = FirebaseDatabase.getInstance().getReference();
                    String uploadID = mFirebase.push().getKey();
                    mFirebase.child(uploadID).setValue(upload);

                    //fl.removeAllViews();

                    FragmentManager fragmentManager = getFragmentManager();
                    FragmentTransaction fragmentTransaction = fragmentManager.beginTransaction();
                    fragmentTransaction.replace(R.id.fragment_container, new NotificationFragment());
                    fragmentTransaction.commit();

                }
            }
        });

        return root;
    }

    public static String getMacAddr() {
        try {
            List<NetworkInterface> all = Collections.list(NetworkInterface.getNetworkInterfaces());
            for (NetworkInterface nif : all) {
                if (!nif.getName().equalsIgnoreCase("wlan0")) continue;

                byte[] macBytes = nif.getHardwareAddress();
                if (macBytes == null) {
                    return "";
                }

                StringBuilder res1 = new StringBuilder();
                for (byte b : macBytes) {
                    res1.append(String.format("%02X:",b));
                }

                if (res1.length() > 0) {
                    res1.deleteCharAt(res1.length() - 1);
                }
                return res1.toString();
            }
        } catch (Exception ex) {
        }
        return "02:00:00:00:00:00";
    }

    private boolean fieldEntry() {

        if(TextUtils.isEmpty(nameEditText.getText().toString().trim())){
            Toast.makeText(getActivity(), "Enter Name", Toast.LENGTH_SHORT).show();
            return false;
        }else if(TextUtils.isEmpty(nameLastEditText.getText().toString().trim())){
            Toast.makeText(getActivity(), "Enter Last Name", Toast.LENGTH_SHORT).show();
            return false;
        }else if(TextUtils.isEmpty(cityEditText.getText().toString().trim())){
            Toast.makeText(getActivity(), "Enter a Email ID", Toast.LENGTH_SHORT).show();
            return false;
        }else if(TextUtils.isEmpty(numberEditText.getText().toString().trim())){
            Toast.makeText(getActivity(), "Enter the Phone Number", Toast.LENGTH_SHORT).show();
            return false;
        }
        return true;
    }
}
